name: Update Runbook Info
on:
  workflow_dispatch:
jobs:
  update_runbook_info_script:
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      pull-requests: read
      contents: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Configure git
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        working-directory: ./.github/runbook
        run: npm install
      - name: Run script
        working-directory: ./.github/runbook
        run: |
          node generate-runbook.mjs
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          openAiApiKey: ${{ secrets.OPENAI_SECRET_KEY }}
          openAiOrg: ${{ secrets.OPENAI_ORG }}
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'runbook/*.json'
          commit_message: "Update Runbook info"